### ISSUE TITLE
Support gin chromedp net/http and other modules for packaging, do you call it on Android?

### ISSUE THREAD

**Issue by passerbyo** [ggdream/bindgo#2]

**Comment by passerbyo** [comment]
https://github.com/gin-gonic/gin

https://github.com/chromedp/chromedp

https://github.com/go-rod/rod

**Comment by ggdream** [comment]
Hi @passerbyo , these libraries can I take the time to make some examples. This repository mainly implements the golang toolchain call and the configuration of the dynamic library referenced by each platform. As long as it can be compiled correctly by golang, it should be fine.
